# coding: utf-8

"""
    Pure Fusion API

    Pure Fusion is fully API-driven. Most APIs which change the system (POST, PATCH, DELETE) return an Operation in status \"Pending\" or \"Running\". You can poll (GET) the operation to check its status, waiting for it to change to \"Succeeded\" or \"Failed\".   # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import fusion
from fusion.api.operations_api import OperationsApi  # noqa: E501
from fusion.rest import ApiException


class TestOperationsApi(unittest.TestCase):
    """OperationsApi unit test stubs"""

    def setUp(self):
        self.api = OperationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_operation(self):
        """Test case for get_operation

        Gets a specific Operation.  # noqa: E501
        """
        pass

    def test_get_operation_by_id(self):
        """Test case for get_operation_by_id

        Gets a specific Operation.  # noqa: E501
        """
        pass

    def test_list_operations(self):
        """Test case for list_operations

        Gets a list of Operations matching the criteria.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
