# coding: utf-8

"""
    Pure Fusion API

    Pure Fusion is fully API-driven. Most APIs which change the system (POST, PATCH, DELETE) return an Operation in status \"Pending\" or \"Running\". You can poll (GET) the operation to check its status, waiting for it to change to \"Succeeded\" or \"Failed\".   # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import fusion
from fusion.api.network_interface_groups_api import NetworkInterfaceGroupsApi  # noqa: E501
from fusion.rest import ApiException


class TestNetworkInterfaceGroupsApi(unittest.TestCase):
    """NetworkInterfaceGroupsApi unit test stubs"""

    def setUp(self):
        self.api = NetworkInterfaceGroupsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_network_interface_group(self):
        """Test case for create_network_interface_group

        (Provider) Creates a Network Interface Group.  # noqa: E501
        """
        pass

    def test_delete_network_interface_group(self):
        """Test case for delete_network_interface_group

        (Provider) Deletes a specific Network Interface Group.  # noqa: E501
        """
        pass

    def test_get_network_interface_group(self):
        """Test case for get_network_interface_group

        (Provider) Gets a specific Network Interface Group.  # noqa: E501
        """
        pass

    def test_get_network_interface_group_by_id(self):
        """Test case for get_network_interface_group_by_id

        (Provider) Gets a specific Network Interface Group.  # noqa: E501
        """
        pass

    def test_list_network_interface_groups(self):
        """Test case for list_network_interface_groups

        (Provider) Gets a list of all Network Interface Groups.  # noqa: E501
        """
        pass

    def test_update_network_interface_group(self):
        """Test case for update_network_interface_group

        (Provider) Updates a Network Interface Group.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
