# coding: utf-8

"""
    Pure Fusion API

    Pure Fusion is fully API-driven. Most APIs which change the system (POST, PATCH, DELETE) return an Operation in status \"Pending\" or \"Running\". You can poll (GET) the operation to check its status, waiting for it to change to \"Succeeded\" or \"Failed\".   # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from fusion.models.list_response_fields import ListResponseFields  # noqa: F401,E501

class AvailabilityZoneList(ListResponseFields):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'items': 'list[AvailabilityZone]'
    }
    if hasattr(ListResponseFields, "swagger_types"):
        swagger_types.update(ListResponseFields.swagger_types)

    attribute_map = {
        'items': 'items'
    }
    if hasattr(ListResponseFields, "attribute_map"):
        attribute_map.update(ListResponseFields.attribute_map)

    def __init__(self, items=None, *args, **kwargs):  # noqa: E501
        """AvailabilityZoneList - a model defined in Swagger"""  # noqa: E501
        self._items = None
        self.discriminator = None
        self.items = items
        ListResponseFields.__init__(self, *args, **kwargs)

    @property
    def items(self):
        """Gets the items of this AvailabilityZoneList.  # noqa: E501

        A JSON array of Availability Zones  # noqa: E501

        :return: The items of this AvailabilityZoneList.  # noqa: E501
        :rtype: list[AvailabilityZone]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this AvailabilityZoneList.

        A JSON array of Availability Zones  # noqa: E501

        :param items: The items of this AvailabilityZoneList.  # noqa: E501
        :type: list[AvailabilityZone]
        """
        if items is None:
            raise ValueError("Invalid value for `items`, must not be `None`")  # noqa: E501

        self._items = items

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AvailabilityZoneList, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AvailabilityZoneList):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
