# coding: utf-8

"""
    Pure Fusion API

    Pure Fusion is fully API-driven. Most APIs which change the system (POST, PATCH, DELETE) return an Operation in status \"Pending\" or \"Running\". You can poll (GET) the operation to check its status, waiting for it to change to \"Succeeded\" or \"Failed\".   # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from fusion.models.resource_patch import ResourcePatch  # noqa: F401,E501

class PlacementGroupPatch(ResourcePatch):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'hm_array': 'NullableString'
    }
    if hasattr(ResourcePatch, "swagger_types"):
        swagger_types.update(ResourcePatch.swagger_types)

    attribute_map = {
        'hm_array': 'hm_array'
    }
    if hasattr(ResourcePatch, "attribute_map"):
        attribute_map.update(ResourcePatch.attribute_map)

    def __init__(self, hm_array=None, *args, **kwargs):  # noqa: E501
        """PlacementGroupPatch - a model defined in Swagger"""  # noqa: E501
        self._hm_array = None
        self.discriminator = None
        if hm_array is not None:
            self.hm_array = hm_array
        ResourcePatch.__init__(self, *args, **kwargs)

    @property
    def hm_array(self):
        """Gets the hm_array of this PlacementGroupPatch.  # noqa: E501


        :return: The hm_array of this PlacementGroupPatch.  # noqa: E501
        :rtype: NullableString
        """
        return self._hm_array

    @hm_array.setter
    def hm_array(self, hm_array):
        """Sets the hm_array of this PlacementGroupPatch.


        :param hm_array: The hm_array of this PlacementGroupPatch.  # noqa: E501
        :type: NullableString
        """

        self._hm_array = hm_array

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PlacementGroupPatch, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PlacementGroupPatch):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
